edlich/education

- Cake-Folder/Schmand-Mandarinen-Kuchen.txt
> Rezept fuer einen Schmand-Mandarinen-Kuchen

- .project
- Cake-Folder/Baileys_Kuchen.txt
- Cake-Folder/Bienenstich.txt
und
Formatierungen + Kommentar in Bienenstich
> Geringfügige Formatierungen in Baileys_Kuchen

- Cake-Folder/Erdbeerkuchen.txt
> Erdbeerkuchen hinzugefügt

- Cook-Folder/BriefmarkenMitSosse.txt
- Pet-Folder/dog-food/cookies-with-cheese.txt
- Pet-Folder/dog-food/cracker-with-peanut-butter.txt
Rezept "BriefmarkenMitSosse.txt" geändert und einen Ordner "Pet-Folder" hinzugefügt für Haustiere von Studenten. Darin sind auch zwei Rezepte enthalten.
> Rezeptaenderung + Ordner hinzugefuegt + Rezept hinzugefuegt

- Pet-Folder/dog-food/diet- vegetable-soup.txt
- Pet-Folder/dog-food/fish-meatball.txt
- Pet-Folder/dog-food/fish-rice-vegetables.txt
Rezepte für Hunde hinzugefügt.
> Rezepte hinzugefuegt

- Wine-Folder/Chardonay.txt
> adding some wine

- Plaetzchen-Folder/Plaetzchen.md
Passend zur Weihnachtszeit ein sehr leichtes Rezept fuer Plaetzchen ;)
> Add Plaetzchen-Folder

- Wine-Folder/Wine.txt
> [ADD] some more wine

- Cook-Folder/Pizzabroetchen.txt
Ich habe dem Cook-Folder ein Rezept für leckere & schnelle Pizzabrötchen hinzugefügt.
> Pizzabrötchen Rezept 

- Cake-Folder/The_Cake_is_Lie.txt
- Cake-Folder/basic.txt
Peter Schulz, Student in HS Emden im Fach Werkzeuge und Verfahren in SWE bei Prof.Dr. Edlich möchte für seine ESA einen Pullrequest bei Edlich machen.
> Peter schulz hse

- Coffee-Folder/Espresso.txt
Eine Checkliste für perfekten Espresso
> Perfekter Espresso

- Cake-Folder/Gedeckter_Apfelkuchen.txt
Bitte bei der ESA **DVCS mit Git (oder Mercurial)** berücksichtigen.
Kurs: Verfahren und Werkzeuge moderner Softwareentwicklung
Semester: WS 15/16
Student: Keno Weßels
> Added an applepie recpe

- Cake-Folder/Schokoküchlein.txt
> Rezept für Schokoküchlein hinzugefügt

- Cook-Folder/Tomaten Avocado Salat
> Create Tomaten Avocado Salat

- Coffee-Folder/Tee.txt
My real name is Dominic Dahnelt
I added this file because of the task DVCS for pattern and tools in modern software-development
> added tutorial for making tea

- Perfect-Education/perfect video-conference evening in moodle.txt
> Aufgabe: DVCS mit Git (oder Mercurial)

- Cook-Folder/Schwarzbiermarinade.txt
Schwarzbiermarinade als Teil der EA. Frohes marinieren!
> Schwarzbiermarinade

- Cake-Folder/Herrentorte.txt
Added a new cake recipe for the perfect evening. Enjoy! :)
> add(File): new Cake, Herrentorte

- Cake-Folder/Gedeckter_Apfelkuchen.txt
- Cake-Folder/Selterskuchen.md
Add new recipe for Selterskuchen and make some spelling corrections.
> Feature selterskuchen+corrections

- Cake-Folder/Oreo-Cheesecake.md
FH Lübeck - VWS EA DVCS mit Git - KOCH - Oreo Cheesecake recipe.
https://github.com/chefkoch666/education/commit/5b96cb76f943f96a702d764a4f669b92601f32a0
> FH Lübeck - VWS EA DVCD mit Git - KOCH - Oreo Cheesecake recipe.

- Cook-Folder/Fraenkisches-Schaeufele.txt
Hallo, Herr Edlich,
hier der Pull-Request für die Einsendeaufgabe.
Viele Grüße
S. Goeß
> Neues Rezept

- Cake-Folder/Jaegermeisterkuchen.txt
Pull request für die Aufgabe "DVCS mit Git" in "Verfahren und Werkzeuge moderner Softwareentwicklung" von Sebastian Hanna.
> Added recipe for jaegermeister cake

- Cocktail-Folder/Mojito
anbei erhalten Sie meinen PullRequest zu einem leckeren alkoholischen Kleingetränk
Beste Grüße
Marcel Manke
> Pull Request ESA5 Mojito Rezept

- Perfect-Education/Method-documentation
Aufgabe: DVCS mit Git
Phil Seelmann
> Add Method-documentation

- Cake-Folder/Schokonusskuchen.md
Rezept für leckeren veganen Schokonusskuchen.
> Veganer Schokonusskuchen

- Perfect-Education/Perfect-CCD-Checklist.txt
Added perfect checklist for Clean Code Development which is usable even without deeper knowledge of patterns and paradigms.Thus enabling even Junior DEVs to use the checklist.
> Perfect CCd-checklist added

- .idea/modules.xml
- .idea/vcs.xml
- education_fork.iml
Die Files sind durch IntelliJ IDEA entstanden, hiermit anfrage zur Löschung.
Die Files werden für das edlich/education Projekt nicht gebraucht.
> Delete junk files

- Perfect-Education/perfectExercisesPreparing.txt
Moin! Hier ist der Gramm, der wohl nördlichste Teilnehmer aus der Punktesammlerstadt. Viele Grüße aus Flensburg . Matthias Gramm, eingeschrieben an der FH Lübeck
> Flensburger Didaktiktipps vom Gramm

- Cake-Folder/Marshmallows.txt
Das Rezept ist lecker, aber danach sieht die Küche entsprechend aus. Besonders wenn Kinder beim Zubereiten mit dabei sind!
> Ein schönes Rezept für Marshmallows zum Selbermachen!

- Cocktail-Folder/Long Island Iced Tea.txt
Adding Long Island Iced Tea for SWT via pull request.
by Michael Richter
> added long island iced tea

- Cake-Folder/Kekse
- Cake-Folder/Koffersuppe.txt
[Kaffeesahne.txt](https://github.com/edlich/education/files/1083286/Kaffeesahne.txt)
[Kaffeeweißer.txt](https://github.com/edlich/education/files/1083287/Kaffeeweisser.txt)
> wolfdeleu Request

- CLI-Folder/README.md
- CLI-Folder/basic-commands.md
- CLI-Folder/git-commands.md
- gaestebuch.txt
neuer Ordner mit hilfreichen Dingen fuer die Kommandozeile
> Cli folder

- Cake-Folder/Kaesekuchen_2.md
- README.md
- gaestebuch.txt
ich habe einfach mal frech in Ihrer readme eine Änderung (Ergänzung) vorgenommen. Wenn Ihnen dass nicht recht ist, bitte ich um Verzeihung... und Sie machen es wieder rückgängig - dafür gibt es ja Versionierungs-Tools ;)
Besten Gruß
kk
> pull request for swt beuth

- Perfect-Education/perfect_telko.txt
Hallo Herr Edlich, 
wenn dieser pull request bei Ihnen ankommt, sag ich Jibbiee und danke an 
Lisa Tagliaferri (https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). 
Britta Gainey
> Added file perfect_telko.txt to subfolder Perfect-Education

- Perfect-Education/PerfectAwesomeListAppProgramming.txt
Pull Request für Abgabeaufgabe (DVCS mit Git) von Martin Stöber
> Added perfect file to build awesome apps

- Cake-Folder/Zitronenschnitten.txt
Hallo ich habe ein neues Kuchenrezept hinzugefügt. Bitte akzeptieren Sie meinen pull request.
Vielen Dank. 
Jessica Arnold
> schnelles und einfaches Rezept

- History-Folder/git-Geschichte.txt
> added git history with txt file

- Cake-Folder/Baileys-Krokant-Kuchen.txt
Pull-Requst für Einsendeaufgabe DVCS (BHTB MIM 12 W17)
Stefan Brautzsch
> Rezept für Baileys-Krokant-Kuchen hinzugefügt

- Cook-Folder/Itzehoer_Allerlei.txt
Moin Endlich!
Habe hier eine wunderbare Verbesserung für das education-repo in Form eines leckeren Rezeptes.
Grüße
Finn
> Kochrezept fuer Itzehoer Allerlei hinzugefuegt :ok_hand:

- Cake-Folder/Erdbeerkuchen_Dietmar.txt
Rezept für ein Blech Erdbeerkuchen (aus Leer)
Bitte mit aufnehmen, sehr lecker :-)
> Erdbeerkuchenrezept von Dietmar (PullRequest)

- Perfect-Education/perfectProjectManagement.txt
ein CLI Tool für Projekt Management (u.a. Gantt Charts) und zehn Punkte für erfolgreiches Projekt Management.
Mit der Bitte um Aufnahme verbleibe ich 
Mit freundlichen 
Grüßen
Alexander Walkenhorst
> perfectProjectManagement

- Perfect-Education/perfectResearchSources
Bitte ins Repository aufnehmen, weil es mehr gibt als nur Google!! :-)
(gerne auch umbenennen in .txt *uuups*)
Viele Grüße
Natalia Prost
> Recherchieren für Fortgeschrittene

- Perfect-Education/perfectMocking.txt
Add information about mockito, a great mocking tool.
> perfect-mocking

- Perfect-Education/perfectLinuxKeyboardCheatSheet.md
> wp04_swt Aufgabe 5 winterb

- Beer-Folder/Beer.txt
A list of awesome must see and drink beer brewery in Berlin. Cheers - Robert Neujahr
> Berlin beer brewery

- CubaLibre.txt
This is the Recipe for Cuba Libre Coctail
Auch im Winter kann man es trinken!
V.Roumoglou
>  Recipe Cuba Libre

- Cocktail-Folder/Mexikaner.txt
- gaestebuch.txt
Leckeres Mexikaner Rezept
Mit besten Grüßen
Patrick Lieske
> Mexikaner Cocktail Rezept hinzugefügt - Eintrag Gästebuch

- Cake-Folder/Kaesekuchen_3.txt
- gaestebuch.txt
Gästebucheintrag erstellt und den besten Käsekuchen hinzugefügt.
> Pull im Rahmen der Aufgabe DVCS mit Git

- Cake-Folder/Marshmallows.txt
- Cake-Folder/Stachelbeertorte.txt
im Zuge des SS18 in Softwaretechnik im Bachelor für Medieninformatik (Online) und der Aufgabe zum Thema Versionskontrolle wollte ihr Repo um ein Rezept für eine leckere Stachelbeertorte erweitern.
Über das Aktzeptieren dieses Pull-Requests würde ich mich sehr freuen.
VG
Daniel Lauermann
> Neues Rezept "Stachbelbeertorte" und Rechtschreibfehlerbeseitigung

- Cook-Folder/Cloudbread.txt
Sehr geehrter Herr Edlich,
im Rahmen der Übungsaufgabe zu Versionskontrolle des Kurses Softwaretechnik SS2018 im Studiengang Medieninformatik Online möchte ich Ihnen diesen Pull Request anbieten der ein neues Rezept (im Markdown Format) für ein LowCarb Fladenbrot enthält.
Beste Grüße
Arne Wieding
> Rezept Cloud Bread - LowCarb Fladenbrot

- Beer-Folder/Beer.md
> Added new beer: Zunft Kölsch

- Cocktail-Folder/FernetCoca.txt
hier etwas für die Cocktail Rezeptesammlung.
Viele Grüße,
Udo Rink
> Datei FernetCoca.txt in Verzeichnis Cocktail-Folder hinzugefuegt

- Cook-Folder/Hefepfannkuchen
Leckere Hefepfannkuchen mit Zucker und Vanillesoße :-)
> Hefepfannkuchen

- Perfect-Education/perfectPuenktlicheAbgabe.txt
Aufgabe: DVCS mit GitHub / GitLab, etc.
> Add Perfect Education Topic - Puenktliche Abgabe

- CLI-Folder/Cheat Sheet.md
Added new reference to Cheat Sheet
> Create Cheat Sheet.md

- Perfect-Education/PerfectFeedback.txt
Pull request for "Einsendeaufgabe DVCS"
> File perfect feedback

- Coffee-Folder/Cappuccino.txt
- Coffee-Folder/Milchschaum.txt
Neue Beschreibung für Cappuccino im Coffee-Folder hinzugefügt.
[Cappuccino.txt](https://github.com/edlich/education/files/2800338/Cappuccino.txt)
> Add description for Cappuccino into Coffee-Folder

- Coffee-Folder/Eiskaffee.txt
- temporaer.txt
Added a new recipe for iced coffee in the Coffee-Folder.
> Recipe for Iced Coffee

- Cocktail-Folder/IDied.txt
- Cocktail-Folder/Mojito.txt
- Take another prost in Mojito.txt
- Added new coktail "I Died" to coktails
> New russian prost and a new cocktail 'IDied.txt'

- Pet-Folder/cat-breeds/norwegianForestCat/characteristics.txt
added norwegian forest cat to cat breed
> New cat breed

- Cake-Folder/Zwiebel-Speck-Kuchen.md
> added a new cake

- Perfect-Education/perfect evening in moodle.txt
Found some small mistakes in "perfect evening in moodle"
>  Fix typo in perfect evening in moodle

- Beer-Folder/Beer.md
> Changes in beer list 

- Perfect-Education/perfectLearning.md
just some thoughts about learning processes
> add a text about learning to the project

- Beer-Folder/Bier Rezept.md
> Bierrezept hinzugefügt

- README.md
> First comment on a pulled project

- Coffee-Folder/TuerkischerMokka.md
... weil's zu Berlin dazugehört ;)
> Kleinen Türkischen Mokka hinzugefügt

- Pet-Folder/dog-food/Hundekekse_mit_2_Zutaten.txt
Ich habe im Pet-Ordner ein neues Rezept für Hunde hinzugefügt.
> Neues Rezept hinzugefuegt

- Pet-Folder/dog-food/Hundekekse_mit_2_Zutaten.txt
Ich habe noch ein Wort, das zu viel war, entfernt.
> Wort gelassen entfernt

- Cook-Folder/Spaghetti a la Carbonara.md
Added an authentic spaghetti a la carbonara receipt.
> Add pasta receipt.

- Pizza-Folder/AmericanPizza.md
> Pizzarezept hinzugefuegt

- Cocktail-Folder/Negroni.txt
Für ESA Versionskontrolle Beuth Softwaretechnik SoSe20, Dominic Hofmeister
> Added new cocktail recipe to Cocktail-Folder.

- Cook-Folder/DhalCurry_SriLanka.txt
Softwaretechnik (BHTB MIB 13 S20) - AUFGABE: Versionskontrolle (12.7.)
Mein GitHubName entspricht meiner Matrikelnummer ;)
> DhalCurry_SriLanka.txt hinzugefügt

- Coffee-Folder/dalgona_coffee
Hallo, ich hoffe, das klappt jetzt. Viele Grüße!
> Ich habe hier ein neues Kaffee Rezept!

- Beer-Folder/Beer.md
- CLI-Folder/shell-commands.md
Datei shell-commands.md im CLI-Folder hinzugefügt und Datei Beer.md im Beer-Folder erweitert.
> Neues CLI Dokument und neues Bier hinzugefügt

- Cake-Folder/Birnenkuchen.txt
Hallo Herr Prof. DR. Edlich,
von mir gibt es einen Pull mit einer Ergänzung zu Ihren Kuchenrezepten (Birnenkuchen). 
Viele Grüße und einen schönen restSonntag
Tino Böhmke
> Brinenkuchen von Tino Boehmke

- Coffee-Folder/ColdeBrew.md
> Add a new coffee

- Plaetzchen-Folder/butterplaetzchen.txt
> Butterplätzchen

- Perfect-Education/perfectKlausurvorbereitung
Neue Datei, wie die Klausurvorbereitung gelingt
> Add perfectKlausurvorbereitung

- Perfect-Education/perfect_DigitalStorytelling.txt
add file perfect_DigitalStorytelling.txt 
ESA_DVCS
> perfect_DigitalStorytelling.txt

- Cake-Folder/VeganCheeseCake
Adding the best vegan cheese cake recipe
> Add Vegan Cheese Cake Recipe

- Cake-Folder/becherkuchen.txt
Easy recipe for the Cake folder
> Add recipe becherkuchen.txt

- Cocktail-Folder/DarkAndStormy.md
fruchtiger Cocktail für Gingerbeer-Liebhaber
> Dark and Stormy

- Cocktail-Folder/Feuerzangenbowle.txt
Added a recipe for "Feuerzangenbowle" since i think it should be here. Great drink with friends and family to recap the year on a cold winter night.
> Added recipe for "Feuerzangenbowle"

- Plaetzchen-Folder/vanillekipferl.md
very popular at christmas time
> add recipe for "Vanillekipferl"

- Cook-Folder/apfelkuechle.md
Im Rahmen meiner Aufgabe DVCS mit GitHub möchte ich diesem Projekt ein Rezept beisteuern.
> add Apfelküchle to Cooking

- Die-Welt.txt
Wem das nicht vom Hocker haut..... Oder an die Bratpfanne delegiert....
> Planetenkunde: Unsere Heimat

- Perfect-Education/PerfectSummary.md
my small contribution to the Perfect Education with my file PerfectSummary used from math.uni-hamburg.de
> Please accept 

- Pizza-Folder/pizza_salami_mit_knoblauch.txt
Neues Pizza Salami Rezept von Duc Ngo Minh, Matrikelnummer: 902494
> Neues Pizza Salami Rezept von Duc Ngo Minh, Matrikelnummer: 902494

- Köfte Rezept.txt
Ein köstliches Köfte Rezept von Ugursay Pürcek
> Add new Köpfte Rezept

- Coffee-Folder/Cappuccino.txt
- Wiki-Folder/Zwergwarzenwal.txt
2. Pull-Request: Push hat geklappt
> Johannes Keller 28.06.2021 Pull-Request 2: Versionskontrolle

- Cocktail-Folder/Fresh Summer Drink.txt
hier ist mein Pull Request für die Einsendeaufgabe Versionskontrolle.
Ich habe einen Drink für die Sommerzeit hinzugefügt.
Mit freundlichen Grüßen 
Fatih Kenar
> Fresh Summer Drink von Fatih Kenar

- Nature-Folder/Bienenwiesen/Nabu - Blumenwiesen anlegen.txt
Hier eine Text vom NABU, wie man eine Blumenwiese für Wildbienen und Insekten anlegen kann.
> Create Nabu - Blumenwiesen anlegen.txt

- Beer-Folder/Vorwort.md
Sehr geehrter Herr Edlich, 
bei dem ganzen Gerede um das Bier kam mir die Sicherheit ein wenig zu kurz.
Ich erbitte hiermit eine Änderung.
Mit freundlichen Grüßen
Dirk Drutschmann
S903016
> Add Safety First

- Cake-Folder/Waffeln_ohne_EI.txt
Bitte das neues Rezept hinzufügen. Es handelt sich hierbei um ein Waffelrezept ohne Eier :-)
> Neues Rezept hinzugefügt

- Cake-Folder/LemonCake.txt
Ich habe ein neues rezept für eine Variation eines Zitronenkuchens hinzugefügt.
> add new recipe for lemon cake

- Cake-Folder/Russischer_Zupfkuchen.tex
- Köfte Rezept.txt
- Köfte Rezept.txt
Credits: Recipe by Rikes Backschule/chefkoch, tex layout by me.
> Added my favourite cake recipe which I thought you need.

- Good-Constructive-Feedback/feedback.txt
Here is example of perfect feedback
> Giving perfect feedback

- Cocktail-Folder/PinaColada.txt
> add a pina coloda recipe

- Cook-Folder/Mediterraner_Nudelsalat.md
Dieses Rezept kann ich empfehlen. Es ist ein Muss in jeder guten Rezeptsammlung ;)
> Leckerer Nudelsalat mit getrockneten Tomaten

- Pizza-Folder/KuerbisPizza.md
Sehr geehrter Herr Edlich,
Für die ESA5 DSVS ein neues Pizza Rezept.
Viele Grüße,
Veronika Simmering
> adding new pizza recipe

- Cocktail-Folder/ginSour.md
> add gin sour recipe

- Cook-Folder/Pasta Verde
Hier ist ein neues Rezept für leckere Pasta Verde ;)
> Neues Rezept für Pasta Verde

- Cake-Folder/Saterlaender-Apfelkuchen.md
Adding a recipe for "Saterländer Apfelkuchen" no one should miss
> Add "Saterländer Apfelkuchen" to cake folder

- Wine-Folder/Gluehwein-Rezept.md
Ein leckeres Glühweinrezept für die kalte Jahreszeit
> Ein leckerer Glühwein

- Art-Folder/chess.txt
In dem Pull Request #317 befindet sich etwas Ascii-Art. 👍
> Chess Art hinzugefügt (Zusatzaufgabe)

- Cook-Folder/Champignons_in_Sahnesauce_mit_Spaetzle.txt
> Champignons in Sahnesauce mit Spätzle

- Cake-Folder/Weihnachtskuchen.md
Abgabe ESA 5 "DVCS" im Modul Moderne Softwareentwicklung - Laura Pichlmeier
> add Weihnachtskuchen Rezept

- Art-Folder/Nike.txt
> New Art File

- Cake-Folder/Baumkuchen.txt
> Rezept für Baumkuchen

- Cocktail-Folder/TequilaSunrise.md
> add tequila sunrise recipe

- Cocktail-Folder/Espresso Martini
Einsendeaufgabe DVC Yana Neutz
> added a new cocktail recipe

- new-year-folder/HappyNewYear.txt
> Bernd Meissner: "Add new years greetings" 

- Perfect-Education/perfect_communication.md
Softwaretechnik (BHTB MIB 13 W21) AUFGABE: Versionskontrolle
> Perfect communication

- Cook-Folder/Nudelauflauf.md
PR zur Aufgabe "Versionskontrolle" - SWT WS 21/22
> Add recipe for "Nudelauflauf"

- Cocktail-Folder/Ipanema.md
> add ipanema recipe

- Soup-Folder/ItalienischeBohnensuppe.txt
Jan Lechner aus dem Softwareechnik Kurs BHTB MIB 13 W21
> new soup added

- Sports-Folder/climbing_videos.md
- Tiramisu.txt
Pull request für die ESA Versionskontrolle
> Julia Schöpp WINFO ESA

- Moodle-Education/Tutorials.txt
- Moodle-Education/Was ist Moodle.txt
- Moodle-Education/Webkonferenzsysteme.txt
- Moscow Mule.txt
- Tiramisu.txt
Name: Daniel Kunst
Matrikelnummer: 900159
Kurs: Softwaretechnik
> Moodle-Education Order hinzugefügt + kleinere Änderungen

- Pizza-Folder/pizza-skript/pizzateig.sh
- Pizza-Folder/pizza-skript/readme.md
Einsendeaufgabe Versionskontrolle Sommersemester 2022 BHT von Till Pistiak
> Shell Skript fuer Pizzateig Rezept hinzugefuegt

- Cake-Folder/LemonTarte.md
SWT ESA_9 von Jann-Niklas Zimmermann
> Add recipe for Lemon Tarte

- Coffee-Folder/Kaffee-Bananen-Smoothie.txt
Pull Request von Britta Vieth für die neunte Einsendeaufgabe des Moduls SWT.
Testweise wurde eine Rezept-Datei hinzugefügt.
> SWT - Vieth: ESA9 - Versionskontrolle

- Git-Basics-Notes/content.md
Zwei Beispiele für mögliche Branchingstrategien hinzugefügt.
Diese Strategien haben sich für mich in der Vergangenheit als nützlich erwiesen. Könnte für neue Nutzer interessant sein
> Branching Strategien absatz hinzugefügt

- Cocktail-Folder/FernetCoca.txt
- Cocktail-Folder/Seaside Fizz.txt
- Cocktail-Folder/Whiskey Sour.txt
Fixed Fernet con Coca and Whiskey Sour
Addet Seaside Fizz
> Rework Cocktails

- Sports-Folder/Formula1ClassOf2022.md
Ein wenig F1 darf in keinem Repository fehlen. :)
> Formula 1 Class of 2022

- Cook-Folder/Hummus.md
Lieblingshummusrezept von Florian Schönsee
> hummus hinzugefügt

- Sports-Folder/MarathonGOAT.md
Pull Request für Moderne Softwareentwicklung
> added the goat

- Perfect-Education/perfect_feedback_for_students.md
There is already a short post on perfect feedback in general. This new addition focuses on perfect feedback to students and provides some interesting sources on the topic.
> Assignment bhtmim w22 deutschlaender

- Cake-Folder/Wackelpuddingkuchen.txt
Ist sehr lecker. Tipp: Quark und Sahne durch Joghurt ersetzen, schmeckt mindestens genauso lecker
> add Rezept für Wackelpuddingkuchen

- Art-Folder/TypeSomething.txt
> add: TypeSomething.txt

- Cake-Folder/Zimtschneckenkuchen.txt
> Neues Rezept für Zimtschneckenkuchen

- Perfect-Education/perfect-way-to-learn-coding.md
Idea: students collect usefull links how to learn coding
> PR: The start to create a  link summary how to learn coding 

- HTTP-Folder/http-codes.md
Quick and simple introduction into http-stauscodes based on http.cat
> create the first iteration of a quick http-status-code-cheatsheet

- Poem-Folder/poems-english.md
- Poem-Folder/poems_french.md
Es handelt sich dabei um französische und englische Gedichte.
> Hallo, ich möchte gerne ein paar Gedichte teilen

- notes/remarkable.md
> feat(docu): create notes folder and write about remarkable and Obsidian

- Rezept - Heißes Wasser.txt
Ein tolles Rezept für heißes Wasser (Achtung Verbrennungsgefahr)
> Ein neues Rezept von Torsten  Leithaus Mat Nr: 919071

- meine-tolle-app/Analyse.txt
- meine-tolle-app/EineWeitereDatei.txt
Im Rahmen der Esa wurde ein neuer Branch erstellt.
> ESA Versionskontrolle

- Nature-Folder/Bienenwiesen/Nabu - Blumenwiesen anlegen.txt
Für die ESA.
Zur der Uhrzeit wenig kreativ ... deswegen auch nur wenig Inhalt ... ;)
> ESA DVC-E1

- Coffee-Folder/Vietnamesicher Kaffee
Zubereitung von traditionell vietnamesischen Kaffee
> Create Vietnamesischer Kaffee

- Mergen
Pull Request Softwaretechnik ESA 9 Wladimir Pushkutse
> Änderung Wladimir Pushkutse

- Blum/Marc Blum.txt
> Folder Blum mit .txt Datei hinzugefügt

- README.md
- swt-useful-links/refactoring-guru.md
Hopefully not too much messing around on the entry page..
- Fixed broken image
- Added a new folder with for useful SWT links and first link to refactoring guru
> SoSe2023 SWT - ESA 11 - Florian Zapf

- Cocktail-Folder/Blue Lagoon.md
> Create Blue Lagoon.md

- gourmet/Kunderezension.txt
- gourmet/Schoko-Senftorte.txt
Ein tolles Rezept und eine nicht ganz so tolle Kundenrezension.
> gourmet folder hinzugefügt

- Mamorkuchen.txt
ein tolles Rezept fr Mamor Kuchen
> Neue Rezept von Glawdys Djago

- Witz-Folder/Witze.txt
Witze.txt wurde um einen Witz erweitert.
- im Rahmen des Moduls Softwaretechnik SoSe2023 von Alicia Berthel
> Witze.txt erweitert

- Witz-Folder/Witze.txt
Added Corny Dad Joke 01: "I'm afraid for the calendar. Its days are numbered."
> Update Witze.txt 

- Perfect-Education/perfectLearningMachineLearning.md
Added a Machine Learning Tutorial file to Perfect Learning, which contains some helpful Books and Links to help students learn Machine Learning.
> Added Machine Learning Tutorial

- http-status-dog/README.md
- http-status-dog/http-status-dog.py
Add learning HTTP status code with funny dog image using python script
> Add http status dog script

- Moodle_Verbesserung.txt
> Verbesserungsvorschlag Moodle

- Plätzchenzeit
Ho Ho Ho! Schmecken lassen und frohe Weihnachten!
Hans Hildebrandt
> Plätzchenrezept

- HTTP-Folder/http-codes.md
http-codes is now 1 step closer to perfection
> http dogs added

- Perfect-Education/perfectVideoconference.txt
Guten Tag Herr Edlich, 
es wäre toll, wenn Sie meine kurze txt für eine perfekte Videokonferenz in ihr repository mergen. 
Viele Grüße
> [ESA5] short description for a perfectVideoconference.txt

- Poem-Folder/poem-about-git.md
Added an educational poem about basic git commands that was written by chat-GPT to poems folder. -JH
> Added poem about git to poems folder

- Cake-Folder/Neujahrskuchen.txt
> Added Recipe for Neujahrskuchen

- Pancake_Rezept.txt
Hab ein Rezept für einfache und leckere Pancakes als text-file hinzugefügt
> Added Pancake recipe - ESA

- Rezept_fuer_Vorlesung_zur_Weihnachtszeit.txt
Ergänzung des Repos im Rahmen der Einsendeaufgabe DVCS.
> Rezept für Weihnachtsplätzchen, die die Vorlesung versüßen.

- Cake-Folder/Marmeladenkekse.txt
Ich würde mich freuen, wenn Sie diese leckeren Marmeladenkekse mal probieren.
> Hinzufügen des Marmeladenkeks-Rezepts.

- Cook-Folder/Rotkohltarte mit Ziegenfrischkäse
> Rotkohltarte mit Ziegenfrischkäse

- Enfache Tabellen im LaTex
Ein paar Beispielen für die einfache Tabellen im LaTex.
> Create Enfache Tabellen im LaTex

- Cocktail-Folder/Sazerac.txt
Hinzugefügtes Rezept für Sazerac Cocktail
> Softwaretechnik WS23: Pull Request Ruben Steijn

- Cocktail-Folder/sexOnTheBeach.txt
> ADD Sex on the Beach recipe

- Kinetose.txt
> Virtual Reality Sickness

- Cocktail-Folder/Loecks Love
Hinzufügen eines neuen Cocktail-Rezeptes im Rahmen der Einsendeaufgabe zum Thema Versionsmanagement.
> Create Loecks Love Cocktail receipe

- Cake-Folder/Blaubeeren-Kaese-Kuchen.txt
> esa9-visionskontrolle; Blaubeeren-Kuchen

- linux_commands.md
Eine detaillierte Liste von Linux Befehlen zum nachschlagen
> added linux commands list

- HelloWord_Ascii/hello_world.py
Für Aufgabe 6 - Tim Chmieletzki
> hello_world_ascii

- A-Git-Guide/README.md
This guide should help to learn and using git easily. Git is fun! :)
> Adding a new feature: Git Guide

- my-online-shop-project/README.md
- my-online-shop-project/src/main/java/com/example/shop/Application.java
- my-online-shop-project/src/main/java/com/example/shop/Product.java
- my-online-shop-project/src/main/java/com/example/shop/ProductManager.java
> Füge mein Online-Shop-Projekt hinzu

- Grundgesetz Artikel 1.txt
Jan Dietrich / Software Technik Pull Request Aufgabe
> Jan Dietrich - Software Technik - added Grundgesetz Artikel 1.txt

- Cake-Folder/Pfannkuchen.txt
Wichtig für einen guten Morgen :)
> Ein Pfannkuchen- bzw. Eierkuchen-Rezept darf nicht fehlen

- Rezept Milchreis.txt
Ein fantastisches Rezept für Milchreis
> Create Rezept Milchreis.txt

- Cake-Folder/Eierkuchen.md
Der cake-Folder wurde um ein Rezept für Eierkuchen erweitert
> Gina wiedemann eierkuchen rezept

- health-tips.md
Added a new file: health-tips.md with a handfull of useful health tips for everyone.
> Add Health tips section to repository

- jokes/funny.txt
Pull Request für die Aufgabe dvc
> Add a folder

- ZimtschneckenPlätzchen.txt
Ein leckeres Rezept für Zimtschnecken Plätzchen.
> Füge Rezept für Zimtschnecken Plätzchen hinzu

- kiWitze.txt
Diese Datei habe ich im Rahmen der ESA DVC-E1 erstellt.
viele Grüße
Raphael Radüge
> kiWitze.txt

- Cocktail-Folder/BahamaMama.txt
Einsendeaufgabe DVC Janin Nestler 
[JaninNestler_git_session.txt](https://github.com/user-attachments/files/20282426/JaninNestler_git_session.txt)
> BahamaMama ist sehr lecker

- Sensorbox/sensorbox.txt
> Pull-Request | Sensorbox

- students/MedHabib99.md
Dieser Pull Request wurde im Rahmen der Einsendeaufgabe DVC-E1 erstellt.
Er fügt die Datei `students/MedHabib99.md` hinzu (kleine Vorstellungs-/Beitragskarte).
Die Änderung ist klein, unkritisch und wurde explizit über die GitHub-Weboberfläche (kein CLI) angelegt.
> Studentenkarte hinzufügen: MedHabib99 (DVC-E1)
